name: etris-plantseg
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch==2.1.2+cu118
      - torchvision==0.16.2+cu118
      - numpy<2
      - pyyaml
      - pillow
      - tqdm
      - wandb
      - lmdb
      - pyarrow==11.0.0
      - regex
      - ftfy
      - loguru
      - pycocotools
      - matplotlib
      - opencv-python-headless
