name: etris
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.5.*
  - torchvision=0.20.*
  - pytorch-cuda=12.1
  - numpy
  - pyyaml
  - pillow
  - matplotlib
  - tqdm
  - loguru
  - regex
  - ftfy
  - pip
  - pip:
      - opencv-python-headless
      - wandb
